# Generated by Django 2.1.4 on 2018-12-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('app', models.CharField(max_length=30)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
